### ISSUE TITLE
Weird issue with modded cave biome generation

### ISSUE THREAD

**Issue by mateus3c** [ViciousBadger/larion-one-continent#4]
So I was playing forge 1.20.1 with Alex's Caves and Larion: Disc World and I noticed that Alex's Caves biomes don't generate when using Larion: Disc World, that would be expect considering the world is now limited but the thing is, I recreated the same world seed, one with only Larion and the other with both Larion and Larion: Disc World - the world that had only Larion generated all Alex's Caves biomes in less than 4000 blocks (because I set the cave biomes to be very common) but the world that had both Larion and Larion: Disc World, even tho it it's limit is 5000 blocks (I later changed the limit to 10000 blocks but still, no difference) it only generated 1 single cave biome, remember, it's the same world seed with the same mods, the only difference was the presence/ausence of Larion: Disc World

I don't really understand why this happens but I hope it's something that can be fixed :/

**Comment by ViciousBadger** [comment]
Hi, I haven't really played with Alex's caves so I'm not sure. One thing tho is that Disc World currently has very little "high continentalness" terrain compared to infinite worldgen.This means dripstone caves are also sort of rare, as they only generate when continentalness is higher than 0.7 or so. Maybe Alex's caves work similarly.

**Comment by ViciousBadger** [comment]
Basically to make the world "taper off" more gradually near the edges instead of abruptly turning from land into ocean at the disc edge. I may have overdone the effect a bit. You can change it in `data/minecraft/worldgen/density_function/overworld/continents.json` in the Disc World zip/jar file, the line that goes `location: 0.75` should be changed to something closer to zero. Maybe try 0.1?

**Comment by ViciousBadger** [comment]
Woo! I think I might make the value lower for everyone in the next update.
